version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: task-trasker-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf  # Монтируем файл конфигурации
    # command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]  # Указываем путь к конфигурационному файлу
    ports:
      - "5432:5432"
  
  app:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: task-trasker-app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
