version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: task-trasker-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db_data:/var/lib/postgresql/data
      # - ./configs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf  # Монтируем файл конфигурации
      # - ./init:/docker-entrypoint-initdb.d  # Подключаем директорию с инициализацией
    ports:
      - "5432:5432"
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: task-trasker-app
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  app_test:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: task-trasker-test
    command: "pytest --cov=app ./tests/ --cov-report html:/home/test_report" # here we want to run tests in docker-comtainer
    profiles:
      - with-test
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/postgres
    volumes:
      - ./test_report:/home/test_report
    depends_on:
      - db

volumes:
  db_data:
  test_report:
