version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: task-trasker-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf  # Монтируем файл конфигурации
    # command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]  # Указываем путь к конфигурационному файлу
    ports:
      - "5432:5432"

volumes:
  db_data:
